version:"3.4"
services:
  mongodb:
	image: mongo:7.0
	container_name: mongodb
	command: ["--replSet", "rs0", "--bind-ip-all", "--port", "27017"]
	ports:
	  - "27017:27017"
	extra_hosts:
	  - "host.docker.internal:host-gateway"
    healthcheck:
	  test: echo "try {rs.status() } catch (err) {rs.initiate({_id:'rs0',members:[{_id:0,'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
	  interval: 5s
	  timeout: 30s
	  start_period: 0s
	  start_interval: 1s
	  retries: 30
	volumes:
	  - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes:
  mongodb_data:
		driver: local
	mongodb_config:
		driver: local

networks:
  default:
    name: microserviceNetwork  